---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: from-catalog-shelf
spec:
  workspaces:
  - name: shared-data
  # All good as of https://github.com/tektoncd/catalog.git and commit e680707
  description: |
    Everything off the shelf (Tekton catalog) to git clone, build, push, and notify on Slack when a step happens
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: docker-url
    type: string
    description: Where to push the app to
  - name: app-url
    type: string
    description: Where to curl to test that the app is up

  # Todo add Slack posts inbetween each
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)

    - name: build-and-push
      runAfter: [clone]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: shared-data
      params:
      - name: IMAGE
        value: $(params.docker-url)

    - name: deploy-it
      runAfter: [build-and-push]
      taskRef: 
        name: kubectl
      params:
      - name: action
        value: apply
      - name: path
        value: /workspace/shared-data/config

    - name: curl-it
      runAfter: [deploy-it]
      taskRef: 
        name: curl
      params:
      - name: url
        value: $(params.app-url)
