apiVersion: apps/v1
kind: Deployment
metadata:
  name: catapp
  labels:
    app: catapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catapp
  template:
    metadata:
      labels:
        app: catapp
    spec:
      containers:
        - name: catapp
          # Todo would be awesome if this was a placeholder to replace with sed
          # based on the resulting image digest from the kaniko build/push task
          image: docker.io/adamroberts/catapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
